In [1]:
# 1. Load the dataset using the appropriate Pandas method and store it in a
# variable named df
import pandas as pd
df = pd.read_csv("C:\\Users\\ntt\\Downloads\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [2]:
# Easy Level (1–10)
# Q1
# Load the dataset and display the first 10 records
df = pd.read_csv("C:\\Users\\ntt\\Downloads\\Bank_customer_churn.csv")
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [4]:
# Q2
# Display the last 15 customers.

df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# Q3
# Show 7 random customer records.
df.sample()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9666,9667,15781689,Macadam,758,Spain,Male,35,5,0.0,2,1,0,95009.6,0

In [9]:
# Q4
# Print complete dataset information and identify:
# • Total columns
# • Data type of each column
# • Missing values
df.info()
df.dtypes
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [10]:
# Q5
# Find missing values in every column.
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
# Q6
# Display only numerical columns.
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [12]:
# Q7
# Generate the statistical summary of numerical columns.
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [14]:
# Q8
# Find duplicate rows and print how many exist.

df.duplicated().sum()

np.int64(0)

In [19]:
# Q9
# Remove duplicate rows and store the cleaned dataset

df_clean = df.drop_duplicates()
print(df_clean.shape)

(10000, 14)

In [23]:

# Q10
# Count how many customers have exited and how many have not exited.
print(df['Age'].value.counts())

AttributeError: 'Series' object has no attribute 'value'

In [31]:
# Medium Level (11–20)
# Q11
# Rename the following columns:
# CustomerId → Customer_ID
# CreditScore → Credit_Score
# EstimatedSalary → Salary
# Exited → Churn
df.rename(columns={'CustomerId':'Customer_ID',
                   'CreditScore':'Credit_Score',
                   'Age':'Salary',
                   'Exited':'Churn'},inplace = True)
df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Salary', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Churn'],
      dtype='object')

In [32]:
# Q12
# Add the prefix
# Bank_
# to every column name.
df.add_prefix("bank")

,bankRowNumber,bankCustomer_ID,bankSurname,bankCredit_Score,bankGeography,bankGender,bankSalary,bankTenure,bankBalance,bankNumOfProducts,bankHasCrCard,bankIsActiveMember,bankEstimatedSalary,bankChurn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [40]:
# Q13
# Convert the Age column into float datatype.
df['RowNumber'] = df['RowNumber'].astype(float)
print(df['RowNumber'].dtype)

float64

In [43]:
# Q14
# Convert the Exited column into string datatype.
df['Churn'] = df['Churn'].astype(str)
print(df['Churn'].dtype)

object

In [46]:
# Q15
# Suppose the Balance column has missing values.
# Replace them using the mean of the Balance column
df["Balance"]= df["Balance"].fillna(df["Balance"].mean())
print(df["Balance"].isnull().sum())

0

In [52]:
# Q16
# Suppose the Age column has missing values.
# Replace them using the median age
age_median = df["bankRowNumber"].median()
df["bankRowNumber"] = df["bankRowNumber"].fillna(age_median)
print(df["bankRowNumber"])

KeyError: 'bankRowNumber'

In [53]:
# Q17
# Display only the first five rows after renaming the columns.
df.head()

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Salary,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Churn
0,1.0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2.0,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3.0,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4.0,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5.0,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [57]:
# Q18
# Create a new DataFrame by dropping these columns:
# RowNumber
# CustomerId
# Surname
# Display the first 10 rows.
dicts ={
    "RowNumber":1223344,
    "Surname":"mandawariya",
}
df.head(10)

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Salary,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Churn
0,1.0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2.0,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3.0,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4.0,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5.0,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6.0,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7.0,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8.0,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9.0,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10.0,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [59]:
# Q19
# Drop the Geography column and display dataset information again.
df.drop("Geography",axis =1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  float64
 1   Customer_ID      10000 non-null  int64
 2   Surname          10000 non-null  object
 3   Credit_Score     10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Salary           10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Churn            10000 non-null  object
dtypes: float64(3), int64(7), object(4)
memory usage: 1.1+ MB

In [60]:
# Q20
# Rename NumOfProducts to Products and HasCrCard to CreditCard.
df.rename(columns = {"NumOfProducts":"Products",
                     "HasCrCard":"CreditCard"}, inplace = True)
df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Salary', 'Tenure', 'Balance', 'Products', 'CreditCard',
       'IsActiveMember', 'EstimatedSalary', 'Churn'],
      dtype='object')

In [64]:
# Hard Level (21–30)
# Q21 (Real Company Task)
# Your manager wants cleaner column names.
# Rename every column as follows:
# RowNumber → Row_No
# CustomerId → Customer_ID
# Surname → Last_Name
# CreditScore → Credit_Score
# Geography → Country
# Gender → Sex
# EstimatedSalary → Salary
# Exited → Target
# Display the first five rows.
df.rename(columns = {'RowNumber':'Row_no',
                     'CustomerId':"customer",
                     "Surname":'Last_Name,'
                     "CreditScore":"Credit_Score",
                     "Geography":"Country",
                       "Gender":"sex",
                       "EstimatedSalary":"Salary",
                       "Exited":"target"},inplace = True)
df.columns

SyntaxError: invalid syntax (848029107.py, line 17)