In [23]:
# Pandas Challenges (Based on Your Notebook)
# Challenge 1 – Complete Data Cleaning
# Your manager gives you a messy dataset.
# Perform all of the following:
# • Load the dataset.
# • Display dataset information.
# • Find missing values.
# • Remove duplicate rows.
# • Fill missing values:
# o Age → median
# o Balance → mean
# • Rename:
# o Target → CustomerStatus
# o AnnualIncome → Income
# • Display the first 15 rows.
# Methods expected:
# read_csv()
# info()
# isnull()
# drop_duplicates()
# median()
# mean()
# fillna()
# rename()
# head()
import pandas as pd
df = pd.read_csv("C:\\Users\\ntt\\Downloads\\Task_dataset.csv")
df.info()
df.head()
df.isnull().sum()
df.drop_duplicates()
df["Age"] = df["Age"].mean()
print(df["Age"])
df["Age"] = df["Age"].median()
print(df["Age"])
df["Age"] = df["Age"].fillna()
print(df["Age"])
df.rename(columns = { 
    "Target":"CustomerStatus",
    "AnnualIncome":"Income"
},inplace =True)
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
0       44.249485
1       44.249485
2       44.249485
3       44.249485
4       44.249485
          ...
1015    44.249485
1016    44.249485
1017    44.249485
1018    44.249485
1019    44.249485
Name: Age, Length: 1020, dtype: float64
0       44.249485
1       44.249485
2       44.249485
3       44.249485
4       44.249485
          ...
1015    44.249485
1016    44.249485
1017    44.249485
1018    44.249485
1019    44.249485
Name: Age, Length: 1020, dtype: float64

ValueError: Must specify a fill 'value' or 'method'.

In [24]:
# Challenge 2 – Banking Report
# The bank wants a numeric report.
# Tasks
# • Select only numeric columns.

# Sumit Sir Notes
# • Display summary statistics.
# • Convert Age and CreditScore to float.
# • Display information again.
df.dtypes
df.describe()
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,44.249485,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,44.249485,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,44.249485,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,44.249485,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,44.249485,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [41]:
# Challenge 3 – Duplicate Investigation
# Find duplicate customers.
# Then
# • Count duplicate rows.
# • Remove duplicates.
# • Print information before and after removing duplicates.
# • Show the last 20 rows.
#df1.duplicated().sum()
df.tail(20)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1000,10643,44.249485,125012.0,18825,761,35977.85,2,Germany,Other,Retail,Stay
1001,10763,44.249485,102965.0,17517,838,115028.54,9,UK,NaN,SME,Stay
1002,10910,44.249485,118506.0,6296,306,81892.13,4,Canada,Male,SME,Churn
1003,10200,44.249485,115052.0,20741,484,190233.86,5,Canada,Male,Retail,Churn
1004,10587,44.249485,NaN,40255,383,168358.60,2,Germany,Male,Corporate,Churn
1005,10798,44.249485,176830.0,7626,688,65481.65,10,France,Male,Retail,Stay
1006,10653,44.249485,NaN,21266,598,142086.70,9,France,Female,Corporate,Stay
1007,10756,44.249485,74430.0,3705,489,29651.23,10,UK,Male,Retail,Churn
1008,10417,44.249485,40417.0,37956,681,23880.19,10,India,Male,Retail,Stay
1009,10499,44.249485,166546.0,12497,643,130886.93,3,UK,Male,SME,Stay
1010,10515,44.249485,199762.0,41808,309,60223.29,10,India,Other,SME,Churn
1011,10457,44.249485,63604.0,27633,804,176354.13,5,Germany,Female,Retail,Stay
1012,10882,44.249485,115417.0,3879,413,76591.00,7,NaN,Male,Corporate,Churn
1013,10531,44.249485,85162.0,32083,654,132742.13,10,Canada,Male,SME,Stay
1014,10181,44.249485,166466.0,44281,662,14415.10,0,Canada,Male,Corporate,Churn
1015,10450,44.249485,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,44.249485,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,44.249485,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,44.249485,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,44.249485,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [45]:
# Challenge 4 – HR Department
# HR wants better column names.
# Rename
# CustomerID → Employee_ID
# Age → EmployeeAge
# Gender → EmployeeGender
# AnnualIncome → Salary
# Target → PromotionStatus
# Then
# • Add prefix
# HR_
# to every column.
# Display 10 random records.
df1.rename(columns = {
    "CustomerId":"Employee_ID",
    "Age":"EmployeeAge",
    "Gender":"EmployeeGender",
    "AnnualIncome":"Salary",
    "Target":"PromotionStatus"
} , inplace = True)
df1.columns
df1.add_prefix("HR_")
df1.head(10)

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,44.249485,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,44.249485,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,44.249485,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,44.249485,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,44.249485,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
5,10006,44.249485,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay
6,10007,44.249485,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn
7,10008,44.249485,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay
8,10009,44.249485,62638.0,24760,663,41901.41,4,France,Other,SME,Stay
9,10010,44.249485,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn

In [49]:
# Challenge 5 – Finance Cleaning
# Finance department reports missing values.

# Sumit Sir Notes
# Tasks
# Fill
# AnnualIncome → Median
# Balance → Mean
# Age → Median
# Then
# Generate descriptive statistics.
age_median = df["AnnualIncome"].median()
df["AnnualIncome"] = df["AnnualIncome"].fillna(age_median)
print(df["AnnualIncome"])

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [58]:
# Challenge 6 – Data Type Audit
# The company says
# Age and AnnualIncome are stored incorrectly.
# Tasks
# Convert
# Age → int
# AnnualIncome → float
# Balance → float
# Target → string
# Print information.
df["Age"]= df["Age"].astype(int)
print(df["Age"].dtype)
df["Balance"] = df["Balance"].astype(float)
print(df["Balance"].dtype)
df["Target"] = df["Target"].astype(str)
print(df["Target"].dtype)
df.info()

int64
float64
object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB

In [66]:
# Challenge 7 – Customer Analytics
# Create a new DataFrame that
# • removes Segment
# • removes Geography
# • removes duplicate rows
# Display
# • first 10 rows
# • dataset information
# • statistical summary
df1.describe()
df1.drop("Segment",axis=1)
df1.drop("Geography",axis=1)
df1.duplicated().sum()
df1.head(10)
df1.info()

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure
count,1020.000000,1.020000e+03,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,4.424948e+01,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,2.701387e-13,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,4.424948e+01,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,4.424948e+01,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,4.424948e+01,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,4.424948e+01,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,4.424948e+01,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [84]:
# Challenge 8 – ML Dataset Preparation
# Prepare a machine learning dataset.
# Perform
# • Remove duplicates
# • Remove CustomerID
# • Remove Segment
# • Fill missing values
# • Rename Target to Output
# Finally
# Display
# head()
# info()
# describe()
# value_counts(Output)

df1.drop_duplicates()
df1.drop("CustomerID",axis = 1)
df1.drop("Segment",axis=1)
df1.rename(columns = {
    "Target":"Output"},inplace = True)
df1.columns
df1.head()

df1.info()
df1.describe()
df1.value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1020 non-null   int64
 1   EmployeeAge      1020 non-null   float64
 2   Salary           967 non-null    float64
 3   Spending         1020 non-null   int64
 4   CreditScore      1020 non-null   int64
 5   Balance          969 non-null    float64
 6   Tenure           1020 non-null   int64
 7   Geography        969 non-null    object
 8   EmployeeGender   968 non-null    object
 9   Segment          969 non-null    object
 10  PromotionStatus  1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

CustomerID  EmployeeAge  Salary    Spending  CreditScore  Balance    Tenure  Geography  EmployeeGender  Segment    PromotionStatus
10499       44.249485    166546.0  12497     643          130886.93  3       UK         Male            SME        Stay               2
10756       44.249485    74430.0   3705      489          29651.23   10      UK         Male            Retail     Churn              2
10643       44.249485    125012.0  18825     761          35977.85   2       Germany    Other           Retail     Stay               2
10417       44.249485    40417.0   37956     681          23880.19   10      India      Male            Retail     Stay               2
10910       44.249485    118506.0  6296      306          81892.13   4       Canada     Male            SME        Churn              2
                                                                                                                                     ..
10338       44.249485    84605.0   47234     375          16407.60   2       Canada     Other           SME        Churn              1
10339       44.249485    122137.0  21253     669          21310.18   0       UK         Female          Corporate  Churn              1
10340       44.249485    90717.0   7199      435          17459.45   6       Canada     Other           SME        Churn              1
10341       44.249485    126966.0  7269      326          17923.77   8       India      Other           SME        Churn              1
10998       44.249485    120531.0  46929     733          147220.82  4       India      Male            SME        Stay               1
Name: count, Length: 782, dtype: int64

In [88]:
# Challenge 9 – Column Transformation
# Create these new columns
# NetWorth = Balance + AnnualIncome
# AgeAfterRetirement = Age + 20
# DoubleCreditScore = CreditScore * 2
# IncomePerMonth = AnnualIncome / 12
# Then
# Display first 15 rows
df1["NettWorth"]=df1["Balance"] +df1 ["AnuualIncome"]
df1["AgeAfterRetirement"]=df1["Age"] + 20
df1["DoubleCreditScore"]= df1["CreditScore"] * 2
df1["IncomePerMonth"]=df1["AnnualIncome"] / 12
print(df1.head())

KeyError: 'AnuualIncome'

In [94]:
# Challenge 10 – Company Report
# Display
# • first five rows

# Sumit Sir Notes
# • last five rows
# • ten random rows
# • dataset information
# • descriptive statistics
# Finally rename
# Target → Customer_Status
df.head()
df.sample(10)

df.info()
df.describe()
df1.rename(columns = {"Target":"Customer_Status"
                     },inplace = True)
df1.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB

Index(['CustomerID', 'EmployeeAge', 'Salary', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'Geography', 'EmployeeGender', 'Segment',
       'PromotionStatus'],
      dtype='object')

In [105]:
# Challenge 11 – Missing Value Report
# Create a report showing
# • Total missing values
# • Numerical columns
# • Mean of Balance
# • Median of Age
# • Fill missing values
# • Display information again

#df=df.isnull().sum()
df["EmployeeGender"] = df["EmployeeGender"].mean()
print(df["EmployeeGender"])

IndexError: invalid index to scalar variable.

In [111]:
# Challenge 12 – Customer Classification
# Count
# Stay

# Churn
# Then
# Rename
# Target → Customer_Class
# Convert it into string.

print(df.["Salary"].value_counts())

SyntaxError: invalid syntax (3434752259.py, line 11)