# Exam Task on Pandas Method (Data Cleaning)

In [18]:
# Part 1 — Inspect & Understand the Dataset
# Q1. Load the dataset
# Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
# Then display the first 10 rows.
# Use: pd.read_csv(), head()
import pandas as pd
df = pd.read_csv("C:\\Users\\ntt\\Downloads\\customer_analytics - customer_analytics (1).csv")
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 0:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 0:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 0:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 0:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 0:00:00,Yes,Medium,11472.36,124,9.1

In [19]:
# Q2. Inspect the end of the dataset
# Display the last 15 rows.
# Use: tail()
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 0:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 0:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 0:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 0:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 0:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 0:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 0:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 0:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 0:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 0:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [20]:
# Q3. Random inspection
# Display 10 random records.
# Use: sample()
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
670,100506,32,236968,248817.49,358,12,Mumbai,SME,Online,2025-12-04 0:00:00,Yes,High,18979.11,69,1.7
1572,101945,63,NaN,90905.25,697,1,Pune,Premium,Online,2024-09-11 0:00:00,Yes,Medium,3944.8,100,2.9
31,100375,65,104561,221128.97,433,1,Delhi,Corporate,Branch,2021-01-31 0:00:00,Yes,High,12395.98,14,5.7
1125,100534,34,37115,76146.32,769,15,Hyderabad,Corporate,Branch,2024-07-23 0:00:00,No,Low,27363.71,29,3.2
952,101937,missing,57174,231134.17,840,6,Pune,Retail,Branch,2023-10-29 0:00:00,NO,Low,48493.82,120,4.9
928,101799,NaN,88278,178242.56,702,8,Bangalore,Retail,Branch,2024-08-19 0:00:00,Yes,Low,1455.31,105,8.3
1659,100801,20,79253,221822.47,656,0,Chennai,Corporate,Agent,NaN,Yes,Medium,20663.08,126,9.1
309,101068,38,209816,164802.79,513,14,Mumbai,Corporate,Branch,2026-02-27 0:00:00,Yes,High,44435.66,125,9.8
1956,100206,28,110530,133036.75,364,4,Pune,Retail,Branch,2023-07-19 0:00:00,Yes,High,11703.38,30,6.2
662,101415,50,215864,101931.07,446,2,Kolkata,SME,Online,2023-06-25 0:00:00,Yes,High,43879.43,137,7.9

In [21]:
# Q4. Dataset audit
# Use info() to identify:
# • Number of rows
# • Number of columns
# • Columns with missing values
# • Columns having incorrect/object datatypes
# Use: info()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [22]:
# Q5. Missing-value audit
# Calculate the number of missing values in every column.
# Then verify the result using both:
# isnull()

# Sumit Sir Notes
# and
# isna()
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [23]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [26]:
# Part 2 — Detect & Fix Data Quality Problems
# Q6. Duplicate investigation
# Find how many duplicate rows exist.
# Do not remove them yet.
# Use: duplicated()

df1.duplicated().sum()

np.int64(40)

In [33]:
# Q7. Remove duplicates
# Remove all duplicate records and store the cleaned result back into df.
# Then verify that duplicates no longer exist.
# Use: drop_duplicates(), duplicated()
df1.duplicated().sum()

np.int64(40)

In [41]:
# Q8. Numeric column investigation
# Select only numeric columns.
# Identify which columns are currently numeric and which potentially numeric columns have
# become object because of invalid values.
# Use: select_dtypes()
df1.dtypes

Customer_ID             int64
Age                    object
Annual_Income          object
Account_Balance        object
Credit_Score           object
Tenure_Years            int64
City                   object
Segment                object
Channel                object
Join_Date              object
Active                 object
Risk_Level             object
Monthly_Spend          object
Transactions           object
Satisfaction_Score    float64
dtype: object

In [49]:
# Q9. Fix Age
# The Age column contains:
# • Valid numbers
# • Missing values
# • Invalid text such as unknown, N/A, etc.
# Convert Age into a proper numeric column.
# Invalid values should become missing values.
# Then fill missing Age values using the median age.

# Sumit Sir Notes
# Use: pd.to_numeric(), median(), fillna()

df1["Age"]  = pd.to_numeric(df1["Age"],errors = "coerce")
df1["Age"]=df1["Age"].median()
print(df1["Age"])
age_median=df1["Age"]
df1['Age'].fillna('unknow',inplace = True )
df1

0       47.0
1       47.0
2       47.0
3       47.0
4       47.0
        ...
2035    47.0
2036    47.0
2037    47.0
2038    47.0
2039    47.0
Name: Age, Length: 2040, dtype: float64

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,47.0,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,47.0,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,47.0,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,47.0,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,47.0,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,47.0,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,47.0,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,47.0,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,47.0,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,47.0,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [55]:
# Q10. Fix Annual Income
# Clean Annual_Income.
# Requirements:
# 1. Convert invalid values to missing.
# 2. Convert the column to a numeric datatype.
# 3. Calculate the median.
# 4. Fill missing values using the median.
# Use: pd.to_numeric(), median(), fillna(), astype()
df1["Annual_Income"]  = pd.to_numeric(df1["Annual_Income"],errors = "coerce")
df1["Annual_Income"]=df1["Annual_Income"].median()
print(df1["Annual_Income"])
df1['Annual_Income'].fillna('unknow',inplace = True)
df1

0       139999.5
1       139999.5
2       139999.5
3       139999.5
4       139999.5
          ...
2035    139999.5
2036    139999.5
2037    139999.5
2038    139999.5
2039    139999.5
Name: Annual_Income, Length: 2040, dtype: float64

C:\Users\ntt\AppData\Local\Temp\ipykernel_18836\1490003719.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Annual_Income'].fillna('unknow',inplace = True )

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,47.0,139999.5,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,47.0,139999.5,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,47.0,139999.5,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,47.0,139999.5,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,47.0,139999.5,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,47.0,139999.5,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,47.0,139999.5,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,47.0,139999.5,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,47.0,139999.5,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,47.0,139999.5,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [63]:
# Part 3 — Numerical Cleaning
# Q11. Clean Account Balance
# The Account_Balance column contains invalid strings and missing values.
# Clean the column and replace missing values with the mean Account Balance.
# Use:
# • pd.to_numeric()
# • mean()
# • fillna()
df1["Account_Balance"]  = pd.to_numeric(df1["Account_Balance"],errors = "coerce")
print(df1["Account_Balance"])
df1["Account_Balance"]=df1["Account_Balance"].mean()
print(df1["Account_Balance"])
df1["Account_Balance"].fillna('unknow',inplace = True)
print(df1["Account_Balance"])
df1

0       151049.054226
1       151049.054226
2       151049.054226
3       151049.054226
4       151049.054226
            ...
2035    151049.054226
2036    151049.054226
2037    151049.054226
2038    151049.054226
2039    151049.054226
Name: Account_Balance, Length: 2040, dtype: float64
0       151049.054226
1       151049.054226
2       151049.054226
3       151049.054226
4       151049.054226
            ...
2035    151049.054226
2036    151049.054226
2037    151049.054226
2038    151049.054226
2039    151049.054226
Name: Account_Balance, Length: 2040, dtype: float64
0       151049.054226
1       151049.054226
2       151049.054226
3       151049.054226
4       151049.054226
            ...
2035    151049.054226
2036    151049.054226
2037    151049.054226
2038    151049.054226
2039    151049.054226
Name: Account_Balance, Length: 2040, dtype: float64

C:\Users\ntt\AppData\Local\Temp\ipykernel_18836\3142562785.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Account_Balance"].fillna('unknow',inplace = True)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,47.0,139999.5,151049.054226,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,47.0,139999.5,151049.054226,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,47.0,139999.5,151049.054226,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,47.0,139999.5,151049.054226,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,47.0,139999.5,151049.054226,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,47.0,139999.5,151049.054226,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,47.0,139999.5,151049.054226,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,47.0,139999.5,151049.054226,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,47.0,139999.5,151049.054226,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,47.0,139999.5,151049.054226,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [66]:
# Q12. Clean Credit Score
# Clean Credit_Score.
# Invalid values should become missing.
# Then replace missing values with the median Credit Score.
# Finally convert the column to integer.
# Use:
# • pd.to_numeric()
# • median()

#• astype()
df1["Credit_Score"]  = pd.to_numeric(df1["Credit_Score"],errors = "coerce")
print(df1["Credit_Score"])
df1["Credit_Score"] = df1["Credit_Score"].median()
print(df1["Credit_Score"])
df1["Credit_Score"] = df1["Credit_Score"].astype(str)
print(df1["Credit_Score"] )

0       570.0
1       570.0
2       570.0
3       570.0
4       570.0
        ...
2035    570.0
2036    570.0
2037    570.0
2038    570.0
2039    570.0
Name: Credit_Score, Length: 2040, dtype: float64
0       570.0
1       570.0
2       570.0
3       570.0
4       570.0
        ...
2035    570.0
2036    570.0
2037    570.0
2038    570.0
2039    570.0
Name: Credit_Score, Length: 2040, dtype: float64
0       570.0
1       570.0
2       570.0
3       570.0
4       570.0
        ...
2035    570.0
2036    570.0
2037    570.0
2038    570.0
2039    570.0
Name: Credit_Score, Length: 2040, dtype: object

In [77]:
# Q13. Clean Monthly Spend
# Clean Monthly_Spend.
# Then:
# • Convert it to numeric.
# • Replace invalid values.
# • Replace missing values using the median.
# • Make sure the final column is numeric.

df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"], errors="coerce")
df["Monthly_Spend"] = df["Monthly_Spend"].fillna(df["Monthly_Spend"].median())

print(df["Monthly_Spend"].dtype)

float64

In [67]:
# Q14. Clean Transactions
# The Transactions column contains invalid strings.
# Convert it to numeric and replace invalid values with the median number of transactions.
# Then convert the final column to integer.
# Convert Transactions to numeric
df["Transactions"] = pd.to_numeric(
    df["Transactions"],
    errors="coerce"
)

transaction_median = df["Transactions"].median()

df["Transactions"] = df["Transactions"].fillna(transaction_median)

df["Transactions"] = df["Transactions"].astype(int)

print(df["Transactions"].dtype)
print(df["Transactions"].head())

int64
0    135
1    106
2    146
3    115
4     94
Name: Transactions, dtype: int64

In [68]:
#Q15. Clean Satisfaction Score
#Clean Satisfaction_Score.
#Replace missing/invalid values using the mean Satisfaction Score.
#Then convert the column to float.
# Convert to numeric
df["Satisfaction_Score"] = pd.to_numeric(
    df["Satisfaction_Score"],
    errors="coerce"
)
satisfaction_mean = df["Satisfaction_Score"].mean()
df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(
    satisfaction_mean
)

df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)

# Check
print(df["Satisfaction_Score"].dtype)
print(df["Satisfaction_Score"].head())

float64
0    3.1
1    8.2
2    6.3
3    9.7
4    3.7
Name: Satisfaction_Score, dtype: float64

In [69]:
# Part 4 — Date Cleaning
# Q16. Investigate Join_Date
# Inspect the Join_Date column.
# Identify the problems caused by:
# • Missing dates
# • Different date formats
# • Invalid date strings

# Sumit Sir Notes
# Do not clean it yet.

print("Missing dates:", df["Join_Date"].isnull().sum())
#Check unique values:
print(df["Join_Date"].unique()[:20])
#Check sample:
print(df["Join_Date"].head(20))
print(df["Join_Date"].value_counts().head(20))

Missing dates: 102
['2022-08-15 0:00:00' '2025-01-11 0:00:00' '2024-08-01 0:00:00'
 '2021-05-15 0:00:00' '2026-02-03 0:00:00' '2023-06-04 0:00:00'
 '2024-01-16 0:00:00' '2024-06-26 0:00:00' '2025-03-12 0:00:00'
 '2021-10-07 0:00:00' '2023-03-02 0:00:00' '2025-11-22 0:00:00'
 '2021-06-25 0:00:00' '2025-11-19 0:00:00' '2025-08-26 0:00:00'
 '2024-05-05 0:00:00' '2022-01-07 0:00:00' '2022-05-25 0:00:00'
 '2022-10-07 0:00:00' '2023-08-10 0:00:00']
0     2022-08-15 0:00:00
1     2025-01-11 0:00:00
2     2024-08-01 0:00:00
3     2021-05-15 0:00:00
4     2026-02-03 0:00:00
5     2023-06-04 0:00:00
6     2024-01-16 0:00:00
7     2024-06-26 0:00:00
8     2025-03-12 0:00:00
9     2021-10-07 0:00:00
10    2023-03-02 0:00:00
11    2025-11-22 0:00:00
12    2021-06-25 0:00:00
13    2025-11-19 0:00:00
14    2025-08-26 0:00:00
15    2024-05-05 0:00:00
16    2022-01-07 0:00:00
17    2022-05-25 0:00:00
18    2022-10-07 0:00:00
19    2023-08-10 0:00:00
Name: Join_Date, dtype: object
Join_Date
not_a_date            12
unknown                8
31/99/2024             6
2022-06-26 0:00:00     5
2022-07-24 0:00:00     5
2025-10-29 0:00:00     5
2023-12-24 0:00:00     5
2025-10-31 0:00:00     5
2024-01-10 0:00:00     5
2022-06-28 0:00:00     5
2023-07-19 0:00:00     5
2022-01-25 0:00:00     5
2025-06-19 0:00:00     4
2023-04-17 0:00:00     4
2022-02-16 0:00:00     4
2022-02-12 0:00:00     4
2024-12-07 0:00:00     4
2023-08-22 0:00:00     4
2023-09-28 0:00:00     4
2022-07-01 0:00:00     4
Name: count, dtype: int64

In [71]:
# 17. Convert Join_Date
# Convert Join_Date into a proper Pandas datetime column.
# Any invalid dates should become missing values.
# Use: pd.to_datetime()
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)
print(df["Join_Date"].dtype)
print(df["Join_Date"].head())

datetime64[ns]
0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
Name: Join_Date, dtype: datetime64[ns]

In [73]:
#Q18. Handle missing dates
#After conversion, find how many missing dates remain.
#Then replace missing dates appropriately using a reasonable date-based strategy.
median_date = df["Join_Date"].median()
df["Join_Date"] = df["Join_Date"].fillna(median_date)

In [74]:
# Part 5 — Categorical Cleaning
# Q19. Clean City
# The City column contains values such as:
# Mumbai
# mumbai
# Mumbai
# mumbai
# Standardize the values so that logically identical cities are represented consistently.
# Then check the unique frequency distribution.
# Use: replace(), value_counts()
df["City"] = df["City"].str.strip().str.title()

print(df["City"].value_counts())

City
Mumbai       314
Hyderabad    298
Delhi        288
Kolkata      276
Pune         274
Chennai      255
Bangalore    254
Name: count, dtype: int64

In [76]:
#Q20. Analyze Segment
#Check the frequency of:
#Retail
#SME
#Corporate
#Premium

#Sumit Sir Notes
#Also determine whether missing values exist.
#Then replace missing Segment values with the most appropriate category based on your
#analysis.
#Use: value_counts(), fillna()
print("Missing Segment:", df["Segment"].isnull().sum())
df["Segment"] = df["Segment"].str.strip()
print(df["Segment"].value_counts())
print("Most common Segment:", most_common_segment)
df["Segment"] = df["Segment"].fillna(most_common_segment)
print(df["Segment"].value_counts())

Missing Segment: 105
Segment
Premium      523
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64
Most common Segment: Premium
Segment
Premium      628
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64

In [86]:
# Part 6 — Column Transformation
# Q23. Rename columns
# Rename these columns:
# Customer_ID → Customer_ID
# Annual_Income → AnnualIncome
# Account_Balance → AccountBalance
# Credit_Score → CreditScore
# Tenure_Years → Tenure
# Join_Date → CustomerJoinDate
# Risk_Level → RiskLevel
# Monthly_Spend → MonthlySpend
# Satisfaction_Score → SatisfactionScore
# Use rename().
# Part 6 — Column Transformation
# Q23. Rename columns
# Rename these columns:
# Customer_ID → Customer_ID
# Annual_Income → AnnualIncome
# Account_Balance → AccountBalance
# Credit_Score → CreditScore
# Tenure_Years → Tenure
# Join_Date → CustomerJoinDate
# Risk_Level → RiskLevel
# Monthly_Spend → MonthlySpend
# Satisfaction_Score → SatisfactionScore
# Use rename().
# Q23. Rename columns

df.rename(columns={
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
}, inplace=True)

# Check the columns
print(df.columns)

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore'],
      dtype='object')

In [88]:
# Q24. Add a prefix
# Add:
# Customer_
# to every column.
# Example:
# Age
# becomes:
# Customer_Age
# Use: add_prefix()
df.add_prefix("Customer_Age")

,Customer_AgeCustomer_ID,Customer_AgeAge,Customer_AgeAnnualIncome,Customer_AgeAccountBalance,Customer_AgeCreditScore,Customer_AgeTenure,Customer_AgeCity,Customer_AgeSegment,Customer_AgeChannel,Customer_AgeCustomerJoinDate,Customer_AgeActive,Customer_AgeRiskLevel,Customer_AgeMonthlySpend,Customer_AgeTransactions,Customer_AgeSatisfactionScore
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646.77,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,2023-08-26 12:00:00,Yes,Low,48511.32,119,3.1

In [89]:
# Q25. Remove unnecessary column

# Sumit Sir Notes
# Determine whether Customer_ID should be retained for analysis.
# Create a cleaned DataFrame without the identifier column.
# Use: drop()

# Part 7 — Create New Columns
# Q26. Create Annual Income in Lakhs
# Create:
# Income_Lakhs
# using:
# AnnualIncome / 100000
# Then check the first 10 records.


df_clean = df.drop(columns=["Customer_ID"])

print(df_clean.head())
print(df_clean.columns)
print("Customer_ID" in df_clean.columns)

  Age AnnualIncome AccountBalance CreditScore  Tenure       City  Segment  \
0  55        44033      111350.85         772       3  Bangalore      SME
1  32       215546      254378.37         374       8      Delhi   Retail
2  23       226403      159975.42         668      12    Chennai  Premium
3  66        87824       295741.6         315      14     Mumbai  Premium
4  67        31570      242423.78         370       4  Bangalore   Retail

  Channel CustomerJoinDate Active RiskLevel  MonthlySpend  Transactions  \
0   Agent       2022-08-15    Yes       Low      23066.19           135
1   Agent       2025-01-11    Yes      High      24646.77           106
2   Agent       2024-08-01     No    Medium      28536.34           146
3   Agent       2021-05-15    Yes      High      12869.71           115
4   Agent       2026-02-03     No      High      34163.02            94

   SatisfactionScore
0                3.1
1                8.2
2                6.3
3                9.7
4                3.7
Index(['Age', 'AnnualIncome', 'AccountBalance', 'CreditScore', 'Tenure',
       'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active', 'RiskLevel',
       'MonthlySpend', 'Transactions', 'SatisfactionScore'],
      dtype='object')
False

In [94]:
# Q27. Create Monthly Income
# Create:
# MonthlyIncome
# using:
# AnnualIncome / 12
# Then create:
# Income_After_Spending
# using:
# MonthlyIncome - MonthlySpend
# Q27 - Monthly Income

# Q27. Create Monthly Income

# Create MonthlyIncome
# df["MonthlyIncome"] = df["AnnualIncome"] / 12

# # Create Income_After_Spending
# df["Income_After_Spending"] = (
#     df["MonthlyIncome"] - df["MonthlySpend"]
# )

# # Display first 10 records
# print(df[
#     [
#         "AnnualIncome",
#         "MonthlySpend",
#         "MonthlyIncome",
#         "Income_After_Spending"
#     ]
# ].head(10))

In [95]:
# Q28. Create Balance-to-Income Ratio
# Create:
# Balance_Income_Ratio
# using:
# AccountBalance / AnnualIncome
# Then inspect the first 10 rows.

# Sumit Sir Notes
# Think carefully about division by zero and missing values.
# Q28. Create Balance-to-Income Ratio

# Convert columns to numeric
df["AccountBalance"] = pd.to_numeric(
    df["AccountBalance"],
    errors="coerce"
)

df["AnnualIncome"] = pd.to_numeric(
    df["AnnualIncome"],
    errors="coerce"
)

# Replace 0 AnnualIncome with NaN
# This prevents division by zero
df["Balance_Income_Ratio"] = (
    df["AccountBalance"] /
    df["AnnualIncome"].replace(0, pd.NA)
)

# Display first 10 rows
print(df[
    [
        "AccountBalance",
        "AnnualIncome",
        "Balance_Income_Ratio"
    ]
].head(10))

   AccountBalance  AnnualIncome  Balance_Income_Ratio
0       111350.85       44033.0              2.528805
1       254378.37      215546.0              1.180158
2       159975.42      226403.0              0.706596
3       295741.60       87824.0              3.367435
4       242423.78       31570.0              7.678929
5       180084.44       37087.0              4.855730
6        99629.81       67229.0              1.481947
7        61030.94           NaN                   NaN
8       221707.97      153267.0              1.446547
9        41126.84           NaN                   NaN

In [98]:
# Part 8 — Final Real-World Cleaning Challenge
# Q29. Prepare the ML-ready dataset
# Perform the following complete pipeline:
# 1. Load the dataset.
# 2. Inspect the first 10 rows.
# 3. Inspect the last 10 rows.
# 4. Inspect 10 random records.
# 5. Run info().
# 6. Check missing values.
# 7. Check duplicates.
# 8. Remove duplicates.
# 9. Clean all numeric columns.
# 10. Convert invalid numeric values to missing.
# 11. Fill numerical missing values appropriately.
# 12. Convert Join_Date to datetime.
# 13. Handle invalid dates.
# 14. Standardize categorical values.
# 15. Clean the binary Active column.
# 16. Rename the columns.
# 17. Remove unnecessary columns.
# 18. Verify the final datatypes.
# 19. Generate descriptive statistics.
# 20. Check categorical distributions.

import pandas as pd

# 1. Load the dataset
df = pd.read_csv("C:\\Users\\ntt\\Downloads\\customer_analytics - customer_analytics (1).csv")
# 2. Inspect the first 10 rows
print(df.head(10))
# 3. Inspect the last 10 rows
print(df.tail(10))
# 4. Inspect 10 random records
print(df.sample(10))
# 5. Run info()
df.info()
# 6. Check missing values
print(df.isnull().sum())



# 7. Check duplicates
print( df.duplicated().sum())


# 8. Remove duplicates
df = df.drop_duplicates()

print(df.duplicated().sum())

# 9 & 10. CLEAN ALL NUMERIC COLUMNS

numeric_columns = [
    "Age",
    "Annual_Income",
    "Account_Balance",
    "Credit_Score",
    "Tenure_Years",
    "Monthly_Spend",
    "Transactions",
    "Satisfaction_Score"
]

# Convert invalid values to NaN
for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )


# 11. Fill numerical missing values

for column in numeric_columns:
    df[column] = df[column].fillna(
        df[column].median()
    )

print(df[numeric_columns].isnull().sum())

# 12 & 13. CLEAN JOIN_DATE
# Convert Join_Date to datetime
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)

print(df["Join_Date"].isnull().sum())


# Fill missing dates using median date
median_date = df["Join_Date"].median()

df["Join_Date"] = df["Join_Date"].fillna(
    median_date
)

print("Missing dates after cleaning:",
      df["Join_Date"].isnull().sum())

# 14. STANDARDIZE CATEGORICAL VALUE

# Clean City
df["City"] = (
    df["City"]
    .str.strip()
    .str.title()
)

print("\nCITY DISTRIBUTION")
print(df["City"].value_counts())


# Clean Segment
df["Segment"] = (
    df["Segment"]
    .str.strip()
)

# Fill missing Segment with most common category
df["Segment"] = df["Segment"].fillna(
    df["Segment"].mode()[0]
)
print(df["Segment"].value_counts())


# Clean Risk_Level
df["Risk_Level"] = (
    df["Risk_Level"]
    .str.strip()
    .str.title()
)

print("\nRISK LEVEL DISTRIBUTION")
print(df["Risk_Level"].value_counts())


# 15. CLEAN BINARY ACTIVE COLUMN


df["Active"] = (
    df["Active"]
    .astype(str)
    .str.strip()
)

df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    "1": "Yes",
    
    "N": "No",
    "NO": "No",
    "no": "No",
    "0": "No"
})

print("\nACTIVE DISTRIBUTION")
print(df["Active"].value_counts())

# 16. RENAME THE COLUMNS


df.rename(columns={
    "Customer_ID": "Customer_ID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
}, inplace=True)


# Check renamed columns
print("\nRENAMED COLUMNS")
print(df.columns)

# 17. REMOVE UNNECESSARY COLUMN

# Customer_ID is an identifier, not a useful ML feature
df_clean = df.drop(
    columns=["Customer_ID"]
)
print(df_clean.head())

# 18. VERIFY FINAL DATATYPES
print(df_clean.dtypes)

# 19. GENERATE DESCRIPTIVE STATISTICS



print(df_clean.describe())

# 20. CHECK CATEGORICAL DISTRIBUTIONS



print(df_clean["City"].value_counts())


print("\nSEGMENT DISTRIBUTION")
print(df_clean["Segment"].value_counts())



print(df_clean["Active"].value_counts())

print(df_clean["RiskLevel"].value_counts())

   Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0       101317  55         44033       111350.85          772             3
1       101001  32        215546       254378.37          374             8
2       101069  23        226403       159975.42          668            12
3       101968  66         87824        295741.6          315            14
4       100530  67         31570       242423.78          370             4
5       101334  68         37087       180084.44          738             1
6       100415  47         67229        99629.81          464             4
7       100983  65           NaN        61030.94          554            15
8       100417  63        153267       221707.97          508             5
9       101472  42       missing        41126.84          556             3

        City    Segment Channel           Join_Date Active Risk_Level  \
0  Bangalore        SME   Agent  2022-08-15 0:00:00    Yes        Low
1      Delhi     Retail   Agent  2025-01-11 0:00:00    Yes       High
2    Chennai    Premium   Agent  2024-08-01 0:00:00     No     Medium
3     Mumbai    Premium   Agent  2021-05-15 0:00:00    Yes       High
4  bangalore     Retail   Agent  2026-02-03 0:00:00     No       High
5    Chennai    Premium   Agent  2023-06-04 0:00:00    Yes        Low
6    Chennai     Retail  Online  2024-01-16 0:00:00    Yes       High
7    Kolkata        SME   Agent  2024-06-26 0:00:00    Yes     Medium
8  Hyderabad    Premium  Mobile  2025-03-12 0:00:00    Yes       High
9    Kolkata  Corporate  Mobile  2021-10-07 0:00:00    Yes     Medium

  Monthly_Spend Transactions  Satisfaction_Score
0      23066.19          135                 3.1
1           NaN          106                 8.2
2      28536.34          146                 6.3
3      12869.71          115                 9.7
4      34163.02           94                 3.7
5      15121.16            6                 8.5
6      17655.61           31                 2.8
7       1720.85          139                 9.7
8      38043.07           76                 7.1
9      11472.36          124                 9.1
      Customer_ID Age Annual_Income Account_Balance Credit_Score  \
2030       100122  41        201611        40736.71          507
2031       101639  61        128850        266135.8          840
2032       101045  33         88037       129948.93          449
2033       101725  43        122756        36633.45          487
2034       101096  18        189232       235131.72          306
2035       101131  42         88530       153490.72          677
2036       101295  31        205738        270989.4          392
2037       100861  25        211994       160507.65          737
2038       101460  64         30105        32117.15          794
2039       101127  55        248332       274980.99          783

      Tenure_Years       City    Segment Channel           Join_Date Active  \
2030            15  Bangalore        SME   Agent  2024-11-03 0:00:00    Yes
2031             9    Kolkata        SME  Mobile  2026-01-15 0:00:00    Yes
2032             8     Mumbai    Premium  Mobile  2022-11-30 0:00:00    Yes
2033             8       Pune        NaN  Mobile  2021-07-04 0:00:00     No
2034            10  hyderabad        SME  Mobile  2025-09-10 0:00:00     No
2035            12  Hyderabad     Retail   Agent  2021-07-10 0:00:00     No
2036             8     Mumbai  Corporate   Agent  2025-07-05 0:00:00    Yes
2037             8    Kolkata     Retail  Online  2022-10-17 0:00:00    Yes
2038             8  Bangalore     Retail   Agent  2023-08-26 0:00:00     No
2039             6    Chennai     Retail  Branch                 NaN    Yes

     Risk_Level  Monthly_Spend Transactions  Satisfaction_Score
2030       High       18815.18           58                 7.2
2031        Low       34300.44           83                 5.0
2032       High  not_available          147                 9.7
2033       High       10165.71           14                 6.4
2034       High       27227.44           85                 5.9
2035     Medium        8455.42          119                 8.6
2036       High       34087.69          134                 2.6
2037        Low       26518.74           87                 1.3
2038        Low       20943.11          107                 9.3
2039        Low       48511.32          119                 3.1
      Customer_ID Age Annual_Income Account_Balance Credit_Score  \
284        101008  50        165146       282763.78          499
1592       101347  69        128892             NaN          356
339        100169  43         48411        97746.94          738
114        101972  23        241997       137232.92          527
1027       100715  36        180683        48844.51          454
312        100046  74         36303        164875.1          416
1180       101652  49        163311        15717.39          732
356        100483  33        227724             NaN          368
1366       101645  41        205231       169625.99          805
2005       100022  19           NaN       278828.01          829

      Tenure_Years       City    Segment Channel           Join_Date Active  \
284              5        NaN        SME  Branch  2024-03-31 0:00:00     No
1592             3     Mumbai        SME  Branch  2021-02-12 0:00:00    Yes
339              7    Kolkata  Corporate  Online  2021-07-06 0:00:00    Yes
114              1  Hyderabad    Premium  Online  2024-07-20 0:00:00    Yes
1027             0    Kolkata     Retail  Branch  2022-01-28 0:00:00    Yes
312              1     Mumbai     Retail  Branch  2022-07-24 0:00:00     No
1180             4    Kolkata    Premium  Branch  2024-08-01 0:00:00    Yes
356             10    Kolkata    Premium  Online  2025-12-10 0:00:00    Yes
1366             7    Chennai        SME  Branch  2024-01-25 0:00:00     no
2005             2      Delhi  Corporate  Mobile  2022-04-22 0:00:00     No

     Risk_Level Monthly_Spend Transactions  Satisfaction_Score
284        High       2310.21          136                 1.9
1592       High      12550.97          132                 6.5
339         Low      18650.03           62                 2.0
114        High      22354.58           77                 6.6
1027       High      12238.83           20                 3.2
312        High      24807.86            1                 9.9
1180        Low       unknown           70                 9.5
356        High        9046.5          142                 8.1
1366        Low      34978.68           59                 4.3
2005        Low      46535.33          141                 9.7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB
Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64
40
0
Age                   0
Annual_Income         0
Account_Balance       0
Credit_Score          0
Tenure_Years          0
Monthly_Spend         0
Transactions          0
Satisfaction_Score    0
dtype: int64
125
Missing dates after cleaning: 0

CITY DISTRIBUTION
City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Name: count, dtype: int64
Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

RISK LEVEL DISTRIBUTION
Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64

ACTIVE DISTRIBUTION
Active
Yes    1345
No      597
nan      58
Name: count, dtype: int64

RENAMED COLUMNS
Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore'],
      dtype='object')
    Age  AnnualIncome  AccountBalance  CreditScore  Tenure       City  \
0  55.0       44033.0       111350.85        772.0       3  Bangalore
1  32.0      215546.0       254378.37        374.0       8      Delhi
2  23.0      226403.0       159975.42        668.0      12    Chennai
3  66.0       87824.0       295741.60        315.0      14     Mumbai
4  67.0       31570.0       242423.78        370.0       4  Bangalore

   Segment Channel CustomerJoinDate Active RiskLevel  MonthlySpend  \
0      SME   Agent       2022-08-15    Yes       Low      23066.19
1   Retail   Agent       2025-01-11    Yes      High      24625.17
2  Premium   Agent       2024-08-01     No    Medium      28536.34
3  Premium   Agent       2021-05-15    Yes      High      12869.71
4   Retail   Agent       2026-02-03     No      High      34163.02

   Transactions  SatisfactionScore
0         135.0                3.1
1         106.0                8.2
2         146.0                6.3
3         115.0                9.7
4          94.0                3.7
Age                         float64
AnnualIncome                float64
AccountBalance              float64
CreditScore                 float64
Tenure                        int64
City                         object
Segment                      object
Channel                      object
CustomerJoinDate     datetime64[ns]
Active                       object
RiskLevel                    object
MonthlySpend                float64
Transactions                float64
SatisfactionScore           float64
dtype: object
               Age   AnnualIncome  AccountBalance  CreditScore       Tenure  \
count  2000.000000    2000.000000     2000.000000  2000.000000  2000.000000
mean     47.006000  138362.001000   151577.633405   576.251500     7.574000
min      18.000000   25163.000000       55.960000   300.000000     0.000000
25%      34.000000   88617.000000    83956.797500   434.000000     4.000000
50%      47.000000  139914.000000   154119.265000   570.500000     8.000000
75%      61.000000  188465.000000   219656.717500   720.250000    12.000000
max      75.000000  249977.000000   299914.140000   850.000000    15.000000
std      16.184991   61981.578361    82603.862653   160.930148     4.610548

                    CustomerJoinDate  MonthlySpend  Transactions  \
count                           2000   2000.000000    2000.00000
mean   2023-08-23 23:16:47.999999744  24846.208835      75.46050
min              2021-01-01 00:00:00    559.580000       1.00000
25%              2022-06-10 12:00:00  13115.135000      40.00000
50%              2023-08-24 00:00:00  24625.170000      76.00000
75%              2024-11-05 00:00:00  36337.937500     112.00000
max              2026-03-13 00:00:00  49942.820000     149.00000
std                              NaN  13850.626971      42.57714

       SatisfactionScore
count        2000.000000
mean            5.609200
min             1.000000
25%             3.600000
50%             5.700000
75%             7.700000
max            10.000000
std             2.527554
City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Name: count, dtype: int64

SEGMENT DISTRIBUTION
Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64
Active
Yes    1345
No      597
nan      58
Name: count, dtype: int64
RiskLevel
High      986
Low       540
Medium    474
Name: count, dtype: int64

In [101]:
df.to_csv("customer_analytics - customer_analytics (1).csv")